Header & Main section
Ndaboom/portofolio pull request #1
Opened 2022-09-21 20:20 UTC by Ndaboom

The header and main section have been added to the home page.

2022-09-21 20:37 UTC, ha-manel requested changes
# STATUS: REQUIRED CHANGES ♻️

## Hi @Ndaboom 👋 
Great job so far, There are some changes that need to be implemented in order to proceed to the next project 👍  

<img src="https://media0.giphy.com/media/z3piokwf0WPH81MOhu/giphy.gif"/>

## Highlights:  
* All tests passed ✔️

## Required Changes:
_Kindly check the comments below_

------
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-21 20:37 UTC, ha-manel commented on index.html
> +        </a>
- [ ] Kindly wrap the hamburger button (mobile menu button) in a `nav` tag instead of the `a` tag for semantic reasons 👍

2022-09-21 20:37 UTC, ha-manel commented on index.html
> +        </div>
- [ ] Kindly replace this `div` element with a `ul` element. Each icon should be inside `a` tag wrapped in `li` 💯

2022-09-21 20:37 UTC, ha-manel commented on assets/style.css
> +}
- [ ] Kindly update `font-family` of the header to make it the same as the one in Figma 💯

2022-09-21 20:37 UTC, ha-manel commented on assets/style.css
> +        width: 40px;
- [ ] Kindly update the color of the social media links and the spacing between them to match the Figma design 👍 Hint: you should put the `color` property in the `a` tag (not the `div`) to apply the style 😄 

## Your design:
![image](https://user-images.githubusercontent.com/50721479/191604913-57ab7b0d-55d9-4968-9056-785185fcf25e.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/191604970-79e33154-6956-4d6c-802d-4b50d222807b.png)

2022-09-21 20:37 UTC, ha-manel commented on index.html
> +    <section id="main_section">
- [ ] Kindly add the background-image of this section (using CSS) as shown in the Figma design.

## Your design:
![image](https://user-images.githubusercontent.com/50721479/191605379-070dde8a-c4d9-402d-a155-e84887deae38.png)

## Figma design:
![image](https://user-images.githubusercontent.com/50721479/191605412-012e383c-817f-47b8-bbc7-bc9d3fb079ee.png)

2022-09-22 11:14 UTC, jasonfelice approved these changes
Hi @Ndaboom, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<p align="center"><img  src="https://media2.giphy.com/media/Zcm5DaspYzhTxstkF4/giphy.gif?cid=ecf05e472vkr75z01b5qlseyap0ylpyn6krdcf0fokyey0cx&rid=giphy.gif&ct=g"/></p>

## Highlights
No linter errors✔️
Good project documentation✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-22 11:14 UTC, jasonfelice commented on assets/style.css
> +}
- [ ] [OPTIONAL] The design will look great if you bold the headline. I highly recommend it!

## Current:
![image](https://user-images.githubusercontent.com/92215878/191731725-a9e95450-13a7-46a7-9b43-16dffe2e61ce.png)

## Figma:
![image](https://user-images.githubusercontent.com/92215878/191731638-c7ee9b2b-98b1-4e19-8046-2ff04e6f79b0.png)

2022-09-22 11:14 UTC, jasonfelice commented on index.html
> +        <ul id="social_media_links">
- [ ] [Optional] Consider using the social icons from the Figma template.

## Current:
![image](https://user-images.githubusercontent.com/92215878/191732171-57bd359a-6b43-49d6-ba4f-0017bd8fb6ed.png)

##  Figma:
![image](https://user-images.githubusercontent.com/92215878/191732318-fa62565a-18b0-44f8-8e94-e3dbb1d98a66.png)

2022-09-22 11:26 UTC, merged