Recent works and contact form added
Ndaboom/portofolio pull request #2
Opened 2022-09-23 15:44 UTC by Ndaboom

This pull request contains recent works and the contact form section

2022-09-23 17:03 UTC, jerryowusu requested changes
Hi @Ndaboom , 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![no-we-were-so-close-pauline-turner-brooks](https://user-images.githubusercontent.com/65233860/192014049-94fe3cdd-e3c9-4a1e-a765-e29a68835e57.gif)


## Highlights
:heavy_check_mark: Good commit messages
:heavy_check_mark: Neat and well organized code
:heavy_check_mark: Excellent readme file

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:03 UTC, jerryowusu commented on assets/style.css
> +}
As stipulated in the project requirement below, kindly use css Grid in the main container that contains all the cards instead of flexbox. You should then use flexbox to lay out the individual card. Please check and rectify that. (check point number 2)

![Screenshot from 2022-09-23 16-24-44](https://user-images.githubusercontent.com/65233860/192007731-ae8ede2d-f8e7-44c7-8887-3cfaf946c6a3.png)

2022-09-23 17:03 UTC, jerryowusu commented on assets/style.css
> +}
As I indicated above :arrow_up: kindly use flex box to layout the individual cards since it is part of the project requirements

2022-09-23 17:03 UTC, jerryowusu commented on assets/style.css
> +}
Please kindly implement the active, pressed and hover effects of all the buttons. It is true that these effects are not seen on mobile versions but it is a must to implement them at this stage of the project :stuck_out_tongue_winking_eye: You can check the desktop side of the figma design for the button effects. :pray:

You can also remove the border from the button since the figma design does not have any border around it.

Your design

![Screenshot from 2022-09-23 16-38-33](https://user-images.githubusercontent.com/65233860/192010061-ea22c330-2bc5-4b57-8cec-5b8239f49837.png)

Figma design

![Screenshot from 2022-09-23 16-38-50](https://user-images.githubusercontent.com/65233860/192010080-666fb1e9-2356-4113-93bf-4b73aca1954b.png)

2022-09-23 17:03 UTC, jerryowusu commented on assets/style.css
> +}
Kindly ensure that your design is as close to the original design as much as possible. Check and rectify this disparity in the design between yours and the figma below. 

Your design

![Screenshot from 2022-09-23 16-58-23](https://user-images.githubusercontent.com/65233860/192013408-fb5d825d-3c78-4efc-b429-3e3dd7eda664.png)

Figma design
![Screenshot from 2022-09-23 16-58-46](https://user-images.githubusercontent.com/65233860/192013430-ff5a8818-50d1-4ccf-afa7-c8fe07630b4e.png)

2022-09-24 09:10 UTC, fobadara requested changes
# REQUIRES CHANGES  ♻️ 
Hi @Ndaboom, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.


 ## Highlights
✅ Linters are passing

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

[OPTIONAL] Kindly revise the best practices for committing and follow them in the future. You need to take note of things like committing regularly, making sure all your commit messages use uppercase and lowercase at the right places and. writing them in the imperative.
[OPTIONAL] I noticed that you named your feature branch development. I think you should avoid names like dev and development at this stage for certain reasons. One of them is that your branch name should be a feature or an action like forms or add_forms for example. Secondly, words like dev and development are used in Git flow (which you will use from React upwards) and you are currently expected to use GitHub flow. This could cause confusion.
[OPTIONAL] Also your PR summary is almost the same as your PR title. You re expected to go into a little detail.
[OPTIONAL] Kindly take note of the following for your README.
  1. Since you don't have a live demo yet remove the section instead of writing no live demo
  2. There are a lot of empty subheadings like setup, installation, and usage. Kindly fill them up. Tell us how we can clone the repo, what we can use your code for and so on. You can check this [repo](https://github.com/fobadara/gcxchange/blob/development/README.md) out
  3. The link to your MIT license is not working

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 09:10 UTC, fobadara commented on index.html
> +                    <button class="btn-primary primary-font-style">See project</button>
[REQUIRED] You didn't correct the effects as requested by the previous reviewer. Kindly fix that. You can have a look at the image below.

|Template 3|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/192088391-816511d1-cb89-4966-aa95-417f9dc62fef.png)|

2022-09-24 09:10 UTC, fobadara commented on index.html
> +                    <button class="btn-primary primary-font-style">See project</button>
[REQUIRED] You didn't correct the effects as requested by the previous reviewer. Kindly fix that. You can have a look at the image below.

|Template 3|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/192088391-816511d1-cb89-4966-aa95-417f9dc62fef.png)|

2022-09-24 09:10 UTC, fobadara commented on index.html
> +                    <button class="btn-primary primary-font-style">See project</button>
[REQUIRED] You didn't correct the effects as requested by the previous reviewer. Kindly fix that. You can have a look at the image below.

|Template 3|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/192088391-816511d1-cb89-4966-aa95-417f9dc62fef.png)|

2022-09-24 09:10 UTC, fobadara commented on index.html
> +                    <button class="btn-primary primary-font-style">See project</button>
[REQUIRED] You didn't correct the effects as requested by the previous reviewer. Kindly fix that. You can have a look at the image below.

|Template 3|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/192088391-816511d1-cb89-4966-aa95-417f9dc62fef.png)|

2022-09-24 09:10 UTC, fobadara commented on index.html
> +                    <button class="btn-primary primary-font-style">See project</button>
[REQUIRED] You didn't correct the effects as requested by the previous reviewer. Kindly fix that. You can have a look at the image below.

|Template 3|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/192088391-816511d1-cb89-4966-aa95-417f9dc62fef.png)|

2022-09-24 09:10 UTC, fobadara commented on index.html
> +        <button class="btn-primary primary-font-style btn-resume">Get My Resume</button>
[REQUIRED] You didn't correct the effects as requested by the previous reviewer. Kindly fix that. You can have a look at the image below.

|Template 3|
|----------|
|![image](https://user-images.githubusercontent.com/62938735/192088391-816511d1-cb89-4966-aa95-417f9dc62fef.png)|

2022-09-24 09:10 UTC, fobadara commented on index.html
> +        <h1 class="primary-font-style contact_form_text">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h1>
[OPTIONAL] Kindly make this text bolder just like in the template. This is only marked as optional because the previous reviewer missed it.

2022-09-24 09:10 UTC, fobadara commented on index.html
> +                <div class="action">
[OPTIONAL] Kindly take note of the corrections in the image below for all your recent works cards.

| Your Design|
|-------------|
|![image](https://user-images.githubusercontent.com/62938735/192089853-ce536d64-a605-4748-aa80-dfd6b6a0fcf0.png)|

2022-09-24 12:56 UTC, awais-amjed approved these changes
# STATUS: APPROVED 🥳

Hi @Ndaboom , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations on implementing the required changes! 🎉👏🥇✨

## Highlights

- [x] Descriptive Pull Request ✔️
- [x] Nice Design ✔️
- [x] Good code organization ✔️ 

![gif](https://media.giphy.com/media/mGK1g88HZRa2FlKGbz/giphy.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 13:10 UTC, merged