Contact form updated
Ndaboom/portofolio pull request #3
Opened 2022-09-27 19:07 UTC by Ndaboom

Section's title color has been updated and fields requirement such as the name has been set up to 30 chars and messages up to 500 chars.

2022-09-27 19:25 UTC, aimalamiri requested changes
Hi @Ndaboom, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-27 19:25 UTC, aimalamiri commented on index.html
>          <form class="input_form">
Good job, but please make sure to add the `method` attribute with a proper value and the `action` attribute with the link to the [Formspree](https://formspree.io/html) form.

2022-09-27 19:25 UTC, aimalamiri commented on index.html
>          <h1 class="primary-font-style contact_form_text">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h1>
It looks nice, but it's a requirement to stick with the Figma design, so please try to follow the exact font size and font weight.

![image](https://user-images.githubusercontent.com/34779928/192615978-309fba74-bf9d-4e95-91a2-e50ceb287b22.png)

2022-09-27 19:25 UTC, aimalamiri commented on index.html
> +            <textarea class="form-input classic-md" name="message" maxlength="500" placeholder="Enter text here" required></textarea>
Your design looks very similar to the one in Figma, but please add some padding to the `inputs` and also decrease the space between inputs as you see in the Figma template.

![image](https://user-images.githubusercontent.com/34779928/192616627-18691e20-1711-4b14-bd3d-d15f5a9845c5.png)

2022-09-27 19:25 UTC, aimalamiri commented on index.html
>          <ul id="social_media_links">
Good job! but I'd recommend fixing the alignment and sizing issue for the social media icons, to make them more beautiful.

![image](https://user-images.githubusercontent.com/34779928/192617319-fd476b55-1644-4c63-94b9-986682ebf2d4.png)

2022-09-28 08:53 UTC, Ndaboom commented on index.html
>          <h1 class="primary-font-style contact_form_text">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h1>
Hi @aimalamiri, the font-weight CSS property is not working as expected. Still looking for a way out.

2022-09-28 09:33 UTC, roshan-bajgain requested changes
Hi @Ndaboom, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 09:33 UTC, roshan-bajgain commented on index.html
>              <input type="submit" class="btn-primary primary-font-style btn-connect" name="submit-form" value="Get in touch" />
- [ ] As requested by the previous reviewer please make sure to stick to the Figma design. There are 5 social icons and please fix the spacing and gaping as well to make similar to the design
### your design
![his](https://user-images.githubusercontent.com/81727988/192743326-724132fb-a3cf-4ed9-8ea3-436f505f6445.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/192743377-4dc587a9-61f5-4b1a-8039-6634fb586d23.png)

2022-09-28 09:33 UTC, roshan-bajgain commented on index.html
>          <h1 class="primary-font-style contact_form_text">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h1>
- [ ] As requested by the previous reviewer please make sure to use the `font-family: 'Inter';` to stick to the design
### Your design
![his](https://user-images.githubusercontent.com/81727988/192744148-2d52ab39-9fd3-4810-850b-75e6a0734ed3.png)
### Figma design
![figma](https://user-images.githubusercontent.com/81727988/192744187-8cece319-11a0-470c-bdbf-d7ac6d1afc28.png)

2022-09-28 10:29 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @Ndaboom 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - Great job making the style as close as much as the Figma design. ✅ ✅ ✅ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 - [OPTIONAL] Branch should have a name of a feature or action (e.g. 'created_sidebar' or 'added_comments_section'). Please remember this in future projects.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 10:33 UTC, merged