Desktop version
Ndaboom/portofolio pull request #4
Opened 2022-09-28 19:25 UTC by Ndaboom

I implement the desktop version based on the mobile version code through CSS media queries.

2022-09-28 22:12 UTC, aimalamiri requested changes
Hi @Ndaboom, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The desktop version is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️

Your project looks very nice 👌But I found some minor issues that you can work one. I'll note some of them in here, and you can check the remaining in the comments.
1. On the header biography section please add some space to the left and right of your text. 

![image](https://user-images.githubusercontent.com/34779928/192897790-906c2e05-5d93-4edc-a0c1-fe6ca2f710ad.png)

3. On the `About me` section you have an image in the right side, but you also need to add one more to the left. So please make sure to add that illustration to left side.
![image](https://user-images.githubusercontent.com/34779928/192897835-24f86387-05d3-4225-9125-76fb21fd71cb.png)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 22:12 UTC, aimalamiri commented on index.html
>          <h1 class="primary-font-style contact_form_text">I'm always interested in hearing about new projects, so if you'd like to chat please get in touch.</h1>
Good job! But please make sure to add the background image like the one in Figma template.

![image](https://user-images.githubusercontent.com/34779928/192894871-5dcd4dee-ddc6-49c6-94a1-f4d31f775f2d.png)

2022-09-28 22:12 UTC, aimalamiri commented on index.html
>              <div class="card">
The project card looks nice, but kindly make sure to align your button to the center of the card.

![image](https://user-images.githubusercontent.com/34779928/192895386-6462b4a9-0229-442c-aea7-c94ece1d47d6.png)

2022-09-28 22:12 UTC, aimalamiri commented on index.html
> +        </nav>
Your navbar looks professional, but don't you think it'll be better to add some margin-bottom so that it'll look more similar to the Figma template?

![image](https://user-images.githubusercontent.com/34779928/192896209-7d5098d7-6f3e-47b1-8497-9165591a3205.png)

2022-09-30 10:28 UTC, Olamarx requested changes
Hi @Ndaboom, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
## The Figma Design
- [ ] Kindly add the image to the other side your as you added it to the right
![image](https://user-images.githubusercontent.com/86200356/193248972-5e0812c4-783c-44a2-aca3-05614f7e5d7b.png)
## Your Design
![image](https://user-images.githubusercontent.com/86200356/193249174-1423f4b2-489a-4cf2-a9ce-eb31ebcc0972.png)

 ## Highlights
- Good commit messages ✔️
- Descriptive readme 👍🏼 
- Good use of Git and GitHub flow ✅ 
- All linters passed ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 16:41 UTC, ichala approved these changes
Hi @Ndaboom ,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  

 
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif)

# To Highlight 💪🏻

- Changes implemted ✔️ 

 Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


*************************************
# Optional Suggestions 

- N/A




_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag  @ichala in your question so I can receive the notification.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 17:04 UTC, merged